# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160301_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location_post),
        ),
    ]
