# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20160229_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('time_accepted', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ManyToManyField(related_name='receiver', to='profiles.UserProfile')),
                ('requester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='profiles.UserProfile')),
            ],
        ),
    ]
