# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Friendship',
        ),
    ]
