# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0002_auto_20160302_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='accepted_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendship',
            name='friends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendship',
            name='sent_status',
            field=models.BooleanField(default=False),
        ),
    ]
