# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160229_0409'),
        ('friendships', '0003_auto_20160302_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='receiver',
        ),
        migrations.AddField(
            model_name='friendship',
            name='receiver',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='profiles.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendship',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='profiles.UserProfile'),
        ),
    ]
