# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[(b'Math 75', b'Math 75'), (b'Math 84', b'Math 84'), (b'Math 85', b'Math 85'), (b'Math 97', b'Math 97'), (b'Math 98', b'Math 98'), (b'Math 99', b'Math 99'), (b'Math 107', b'Math 107'), (b'Math 130', b'Math 130'), (b'Math 132', b'Math 132'), (b'Math 138', b'Math 138'), (b'Math 141', b'Math 141'), (b'Math 142', b'Math 142'), (b'Math 148', b'Math 148'), (b'Math 151', b'Math 151'), (b'Math 152', b'Math 152'), (b'Math 153', b'Math 153'), (b'Math 208', b'Math 208'), (b'Math 238', b'Math 238'), (b'Math 240', b'Math 240'), (b'Math 254', b'Math 254'), (b'Math 342', b'Math 342')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile')),
            ],
        ),
    ]
