# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quarter',
            field=models.CharField(default='spring2015', max_length=50),
            preserve_default=False,
        ),
    ]
