# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, choices=[(b'Finance', b'Finance'), (b'Accounting', b'Accounting'), (b'Marketing', b'Marketing'), (b'Human Resources', b'Human Resources'), (b'Economics', b'Economics'), (b'Computer Science', b'Computer Science'), (b'English', b'English'), (b'History', b'History')], max_length=30, null=True),
        ),
    ]
